version: '3.8'
services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./www/src
  #   container_name: up-it-app
  #   ports:
  #     - 3333:3333
  #   command: pnpm run dev
  #   networks:
  #     - db-network

  db:
    image: postgres:15.3-alpine
    container_name: up-it-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: up-it-db
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - db-network

networks:
  db-network:
    driver: bridge